events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('impressum/', views.impressum_view, name='impressum'),
    path('information/', views.information, name='information'),

    # Other URL patterns for the events app
]

sommer_event/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models

#app views


class Events(models.Model):
    DAY_CHOICES = [
        ('Montag', 'Montag'),
        ('Dienstag', 'Dienstag'),
        ('Mittwoch', 'Mittwoch'),
        ('Donnerstag', 'Donnerstag'),
        ('Freitag', 'Freitag'),
        ('Samstag', 'Samstag'),
        ('Sonntag', 'Sonntag'),
    ]

    datum = models.DateField()
    day = models.CharField(max_length=50, choices=DAY_CHOICES)
    time = models.TimeField()
    street_name = models.CharField(max_length=100)
    house_number = models.CharField(max_length=10, default='')
    postal_code = models.CharField(max_length=6, default='')
    city = models.CharField(max_length=100, null=True, default="")

    filmname = models.CharField(max_length=100)
    trailer = models.URLField()

    def __str__(self):
        return self.filmname
        #get formated adress
    @property
    def formatted_address(self):
        return f"{self.street_name} {self.house_number}, {self.postal_code} {self.city}"

class EventImage(models.Model):
    event = models.ForeignKey(Events, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='event_images')

    def __str__(self):
        return f"{self.event.filmname}"

class Impressum(models.Model):
    impressum = models.TextField(verbose_name='Impressum', default='')
    contact_info = models.TextField(verbose_name='Kontaktinformationen', default='')
    geschaeftsfuehrung = models.TextField(verbose_name='geschaeftsfuehrung', default='')
    datenschutz = models.TextField(verbose_name='Datenschutz', default='')

    def __str__(self):
        return self.impressum if self.impressum else "No Impressum"

class InformationImage(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='information_images')

    def __str__(self):
        return self.name

events/views.py
from django.shortcuts import render
from .models import Events, Impressum, InformationImage, Impressum

def index(request):
    events = Events.objects.all()
    context = {
        'events': events,
    }
    return render(request, 'events/event_list.html', context)


def information(request):
    images = InformationImage.objects.all()
    context = {
        'images': images
    }
    return render(request, 'events/information.html', context)


def impressum_view(request):
    impressum_item = Impressum.objects.get(id=2)  # Adjust the query to fetch the correct Impressum object
    return render(request, 'events/impressum.html', {'item': impressum_item})

events/templates/events/event_list.html
{% extends "events/layout.html" %}

{% block content %}
<!-- Carousel -->
<div id="carousel" class="owl-carousel carousel">">
    {% for event in events %}
        {% for image in event.images.all %}
            <div class="item">
                <img src="{{ image.image.url }}" alt="{{ event.filmname }}" class="carousel-image fit-image">
            </div>
        {% endfor %}
    {% endfor %}
</div>

<section class ="intro-area white " id ="intro">
    <div class="container">
         <div class="row">
             <div class ="col-sm-12 text-center">
                 <h2> Willkommen zum DHL Sommerkino!</h2>
                 <div class ="sub-heading">
                     <p>
                        Wir laden dich, deine Familie, Freunde, Bekannten und alle Nachbarn
                        des DHL Drehkreuz Leipzig zum traditionellen Sommerkino ein.<br>
                        Hier findest du alle Informationen zu den kommenden Veranstaltungen.<br>
                        Freu dich auf spannende Filme, gemütliche Atmosphäre und unvergessliche Sommerabende.<br>
                        Bleib auf dem Laufenden und verpasse keine Filme!
                     </p>



                 </div>
             </div>


         </div>
         </div>
        </section>


<div class="table-container">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Film Titel</th>
                <th>Datum</th>
                <th>Tag</th>
                <th>Zeit</th>
                <th>Adresse</th>
                <th>Trailer ansehen</th>
            </tr>
        </thead>
        <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ event.filmname }}</td>
                    <td>{{ event.datum }}</td>
                    <td>{{ event.day }}</td>
                    <td>{{ event.time }}</td>
                    <td>
                        <a href="https://www.google.com/maps/place/{{ event.formatted_address }}" target="_blank" class="trailer-button external-link">{{ event.formatted_address }}</a>
                    </td>
                    <td>
                        <a href="{{ event.trailer }}" target="_blank" class="trailer-button external-link">{{ event.filmname }}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>
$(document).ready(function() {
    $("#carousel").owlCarousel({
        items: 1,
        loop: true,
        nav: true,
        dots: true,
        autoplay: true,
        autoplayTimeout: 5000,
        autoplayHoverPause: true
    });
});
</script>
{% endblock %}

events/templates/events/footer.html
{% load static %}
<footer class="main-footer" style="background-color: #d3d3d3;">
    <div class="pull-right hidden-xs">
        Customized by Your Company Name
    </div>
    <strong>&copy; 2024 Dhl <a href="https://www.yourcompany.com">Your Company</a>.</strong> All rights reserved.
</footer>

events/templates/events/impressum.html
{% extends 'events/layout.html' %}

{% block content %}
<div class="impressum">

    {% if item %}

    <h2><span class="underline">Rec</span>htliche Hinweise</h2>

        <div class="impressum-section">
            <h4>Impressum</h4>
            <div class="content_imp">
                {% if item.impressum %}
                    {% for line in item.impressum.splitlines %}
                        <p>{{ line }}</p>
                    {% endfor %}
                {% else %}
                    <p>No impressum</p>
                {% endif %}
            </div>
        </div>

        <div class="impressum-section">
            <h4>Kontaktinformationen</h4>
            <div class="content_imp">
                {% if item.contact_info %}
                    {% for line in item.contact_info.splitlines %}
                        <p>{{ line }}</p>
                    {% endfor %}
                {% else %}
                    <p>No contact info</p>
                {% endif %}
            </div>
        </div>

        <div class="impressum-section">
            <h4>Geschäftsführung</h4>
            <div class="content_imp">
                {% if item.geschaeftsfuehrung %}
                    {% for line in item.geschaeftsfuehrung.splitlines %}
                        <p>{{ line }}</p>
                    {% endfor %}
                {% else %}
                    <p>No geschaeftsfuehrung</p>
                {% endif %}
            </div>
        </div>

        <div class="impressum-section">
            <h4>Datenschutz</h4>
            <div class="content_imp">
                {% if item.datenschutz %}
                    {% for line in item.datenschutz.splitlines %}
                        <p>{{ line }}</p>
                    {% endfor %}
                {% else %}
                    <p>No datenschutz</p>
                {% endif %}
            </div>
        </div>

    {% else %}
        <!-- Handle case when item is not found -->
        <p>No item found</p>
    {% endif %}

</div>
{% endblock %}

events/templates/events/information.html
{% extends "events/layout.html" %}

{% block content %}
    <style>
        html, body {
            height: 100%;
            margin: 0;
            font-family: Arial, sans-serif;
        }
        body {
            display: flex;
            justify-content: center;
            align-items: center;
           /* background-color: #FFCC00; */

    background: linear-gradient(to bottom, #FFCC00 45%, #FFFF99 100%);
        }
        .content-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding-top: 215px; /* Adjust this value to increase/decrease the space between the nav and the image */
    padding-left: 20px; /* Adjust this value to increase/decrease the space on the left */
    padding-right: 20px; /* Adjust this value to increase/decrease the space on the right */

        }
        .content-wrapper img {
            max-width: 45%;
            height: auto;
            margin-bottom: 20px;


        }

        @media screen and (max-width: 100%) { /* adjust this value to the breakpoint you want */
    .content-wrapper {
        padding-top: -50px; /* for smaller screens */
    }
}
    </style>

    <div class="content-wrapper">
        {% for image in images %}
           <!-- <h2>{{ image.name }}</h2> -->
            <img src="{{ image.image.url }}" alt="{{ image.name }}">
        {% endfor %}
    </div>
{% endblock %}

events/templates/events/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DHL Sommerkino</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Include Owl Carousel CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
</head>
<body>
    <header>
        <div class="container">
            <div class ="row">
                <a href="{% url 'events:index' %}" class ="logo"><img src ="{% static 'images/logo.png' %}" alt="DHL Logo" style="width: 100px; height: auto;"></a>
                <nav>
                    <ul>
                        <li class="home-link"><a href="{% url 'events:index' %}">Home</a></li>
                        <li><a href="{% url 'events:information' %}">Information</a></li>
                        <li><a href="{% url 'events:impressum' %}">Impressum</a></li>

                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-block">
            <p>&copy; 2024 DHL Hub Leipzig GmbH</p>
        </div>
        <div class="footer-block">
            <li><a href="{% url 'events:impressum' %}">Impressum</a></li>
        </div>
        <div class="social-icons">
            <a href="https://www.facebook.com/hubleipzig" target="_blank" class="external-link"><i class="uil uil-facebook-f"></i></a>
            <a href="https://www.linkedin.com/company/hubleipzig/" target="_blank" class="external-link"><i class="uil uil-linkedin"></i></a>
            <a href="https://www.instagram.com/hubleipzig/" target="_blank" class="external-link"><i class="uil uil-instagram"></i></a>
            <a href="https://www.youtube.com/@DHLHubLeipzig" target="_blank" class="external-link"><i class="uil uil-youtube"></i></a>
        </div>
    </footer>

    <!-- Modal HTML structure -->
    <div id="customModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Du verlässt gleich die dhl-sommerkino.de Website. Möchtest du fortfahren? </p>
            <button id="confirmButton">Ja</button>
            <button id="cancelButton">Nein</button>
        </div>
    </div>

    <!-- Include jQuery first, then Owl Carousel -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

    <script>
        function showPopupMessage(event) {
            event.preventDefault(); // Prevent the link from opening immediately
            var modal = document.getElementById("customModal");
            var confirmButton = document.getElementById("confirmButton");
            var cancelButton = document.getElementById("cancelButton");
            var linkHref = event.currentTarget.getAttribute("href"); // Store the href of the clicked link

            modal.style.display = "block"; // Show the modal

            confirmButton.onclick = function() {
                window.open(linkHref, "_blank"); // Open the link in a new tab if confirmed
                modal.style.display = "none"; // Hide the modal
            };

            cancelButton.onclick = function() {
                modal.style.display = "none"; // Hide the modal
            };

            var closeButton = document.getElementsByClassName("close")[0];
            closeButton.onclick = function() {
                modal.style.display = "none"; // Hide the modal
            };

            window.onclick = function(event) {
                if (event.target == modal) {
                    modal.style.display = "none"; // Hide the modal if the user clicks outside of it
                }
            };
        }

        window.addEventListener("DOMContentLoaded", function() {
            var externalLinks = document.getElementsByClassName("external-link");
            for (var i = 0; i < externalLinks.length; i++) {
                externalLinks[i].addEventListener("click", function(event) {
                    showPopupMessage(event);
                });
            }
        });

        $(document).ready(function() {
            $("#carousel").owlCarousel({
                items: 1,
                loop: true,
                nav: true,
                dots: true,
                autoplay: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true
            });
        });
    </script>

    {% block scripts %}
    {% endblock %}
</body>
</html>